// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEMx0gAKyKfpzz5jXwIRDjM3mwJLJNQvw',
    appId: '1:347082193055:web:553dbd6026d02015a84aaa',
    messagingSenderId: '347082193055',
    projectId: 'lizard-app-6a1e8',
    authDomain: 'lizard-app-6a1e8.firebaseapp.com',
    storageBucket: 'lizard-app-6a1e8.firebasestorage.app',
    measurementId: 'G-SYYM3VG964',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCqG0jRsYi-Q21V-xKDI4blJhjVdTkrZI',
    appId: '1:347082193055:android:1977a8a7485ba0f2a84aaa',
    messagingSenderId: '347082193055',
    projectId: 'lizard-app-6a1e8',
    storageBucket: 'lizard-app-6a1e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXbJQo5KgrR-0pGFmvum1Y8-FgwNEDzu4',
    appId: '1:347082193055:ios:c18bc51005933ea5a84aaa',
    messagingSenderId: '347082193055',
    projectId: 'lizard-app-6a1e8',
    storageBucket: 'lizard-app-6a1e8.firebasestorage.app',
    iosBundleId: 'com.example.ecommerenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXbJQo5KgrR-0pGFmvum1Y8-FgwNEDzu4',
    appId: '1:347082193055:ios:c18bc51005933ea5a84aaa',
    messagingSenderId: '347082193055',
    projectId: 'lizard-app-6a1e8',
    storageBucket: 'lizard-app-6a1e8.firebasestorage.app',
    iosBundleId: 'com.example.ecommerenceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEMx0gAKyKfpzz5jXwIRDjM3mwJLJNQvw',
    appId: '1:347082193055:web:63cd1d858131c512a84aaa',
    messagingSenderId: '347082193055',
    projectId: 'lizard-app-6a1e8',
    authDomain: 'lizard-app-6a1e8.firebaseapp.com',
    storageBucket: 'lizard-app-6a1e8.firebasestorage.app',
    measurementId: 'G-B5M4LJ0S0P',
  );

}